export const match = {
  params: {
    owner: 'facebook',
    repo: 'flow',
  },
};

export const repository = {
  id: 25880891,
  node_id: 'MDEwOlJlcG9zaXRvcnkyNTg4MDg5MQ==',
  name: 'flow',
  full_name: 'facebook/flow',
  private: false,
  owner: {
    login: 'facebook',
    id: 69631,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
    avatar_url: 'https://avatars3.githubusercontent.com/u/69631?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/facebook',
    html_url: 'https://github.com/facebook',
    followers_url: 'https://api.github.com/users/facebook/followers',
    following_url: 'https://api.github.com/users/facebook/following{/other_user}',
    gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
    organizations_url: 'https://api.github.com/users/facebook/orgs',
    repos_url: 'https://api.github.com/users/facebook/repos',
    events_url: 'https://api.github.com/users/facebook/events{/privacy}',
    received_events_url: 'https://api.github.com/users/facebook/received_events',
    type: 'Organization',
    site_admin: false,
  },
  html_url: 'https://github.com/facebook/flow',
  description: 'Adds static typing to JavaScript to improve developer productivity and code quality.',
  fork: false,
  url: 'https://api.github.com/repos/facebook/flow',
  forks_url: 'https://api.github.com/repos/facebook/flow/forks',
  keys_url: 'https://api.github.com/repos/facebook/flow/keys{/key_id}',
  collaborators_url: 'https://api.github.com/repos/facebook/flow/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/facebook/flow/teams',
  hooks_url: 'https://api.github.com/repos/facebook/flow/hooks',
  issue_events_url: 'https://api.github.com/repos/facebook/flow/issues/events{/number}',
  events_url: 'https://api.github.com/repos/facebook/flow/events',
  assignees_url: 'https://api.github.com/repos/facebook/flow/assignees{/user}',
  branches_url: 'https://api.github.com/repos/facebook/flow/branches{/branch}',
  tags_url: 'https://api.github.com/repos/facebook/flow/tags',
  blobs_url: 'https://api.github.com/repos/facebook/flow/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/facebook/flow/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/facebook/flow/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/facebook/flow/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/facebook/flow/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/facebook/flow/languages',
  stargazers_url: 'https://api.github.com/repos/facebook/flow/stargazers',
  contributors_url: 'https://api.github.com/repos/facebook/flow/contributors',
  subscribers_url: 'https://api.github.com/repos/facebook/flow/subscribers',
  subscription_url: 'https://api.github.com/repos/facebook/flow/subscription',
  commits_url: 'https://api.github.com/repos/facebook/flow/commits{/sha}',
  git_commits_url: 'https://api.github.com/repos/facebook/flow/git/commits{/sha}',
  comments_url: 'https://api.github.com/repos/facebook/flow/comments{/number}',
  issue_comment_url: 'https://api.github.com/repos/facebook/flow/issues/comments{/number}',
  contents_url: 'https://api.github.com/repos/facebook/flow/contents/{+path}',
  compare_url: 'https://api.github.com/repos/facebook/flow/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/facebook/flow/merges',
  archive_url: 'https://api.github.com/repos/facebook/flow/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/facebook/flow/downloads',
  issues_url: 'https://api.github.com/repos/facebook/flow/issues{/number}',
  pulls_url: 'https://api.github.com/repos/facebook/flow/pulls{/number}',
  milestones_url: 'https://api.github.com/repos/facebook/flow/milestones{/number}',
  notifications_url: 'https://api.github.com/repos/facebook/flow/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/facebook/flow/labels{/name}',
  releases_url: 'https://api.github.com/repos/facebook/flow/releases{/id}',
  deployments_url: 'https://api.github.com/repos/facebook/flow/deployments',
  created_at: '2014-10-28T17:17:45Z',
  updated_at: '2019-07-07T10:20:37Z',
  pushed_at: '2019-07-07T11:28:29Z',
  git_url: 'git://github.com/facebook/flow.git',
  ssh_url: 'git@github.com:facebook/flow.git',
  clone_url: 'https://github.com/facebook/flow.git',
  svn_url: 'https://github.com/facebook/flow',
  homepage: 'https://flow.org/',
  size: 52779,
  stargazers_count: 19719,
  watchers_count: 19719,
  language: 'OCaml',
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  forks_count: 1676,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 2496,
  license: {
    key: 'mit',
    name: 'MIT License',
    spdx_id: 'MIT',
    url: 'https://api.github.com/licenses/mit',
    node_id: 'MDc6TGljZW5zZTEz',
  },
  forks: 1676,
  open_issues: 2496,
  watchers: 19719,
  default_branch: 'master',
  permissions: {
    admin: false,
    push: false,
    pull: true,
  },
  organization: {
    login: 'facebook',
    id: 69631,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
    avatar_url: 'https://avatars3.githubusercontent.com/u/69631?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/facebook',
    html_url: 'https://github.com/facebook',
    followers_url: 'https://api.github.com/users/facebook/followers',
    following_url: 'https://api.github.com/users/facebook/following{/other_user}',
    gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
    organizations_url: 'https://api.github.com/users/facebook/orgs',
    repos_url: 'https://api.github.com/users/facebook/repos',
    events_url: 'https://api.github.com/users/facebook/events{/privacy}',
    received_events_url: 'https://api.github.com/users/facebook/received_events',
    type: 'Organization',
    site_admin: false,
  },
  network_count: 1676,
  subscribers_count: 422,
};

export const activityData = {
  all: [
    50,
    54,
    18,
    7,
    48,
    37,
    46,
    50,
    32,
    34,
    31,
    47,
    97,
    55,
    73,
    69,
    62,
    36,
    36,
    21,
    72,
    50,
    27,
    69,
    7,
    25,
    41,
    29,
    55,
    57,
    46,
    27,
    24,
    25,
    22,
    28,
    38,
    31,
    26,
    42,
    12,
    34,
    18,
    18,
    27,
    67,
    54,
    61,
    53,
    23,
    75,
    31,
  ],
  owner: [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
  ],
};

export const effectiveHours = [
  { name: 1, value: { hours: 100, commits: 50 } },
  { name: 2, value: { hours: 108, commits: 54 } },
  { name: 3, value: { hours: 36, commits: 18 } },
  { name: 4, value: { hours: 14, commits: 7 } },
  { name: 5, value: { hours: 96, commits: 48 } },
  { name: 6, value: { hours: 74, commits: 37 } },
  { name: 7, value: { hours: 92, commits: 46 } },
  { name: 8, value: { hours: 100, commits: 50 } },
  { name: 9, value: { hours: 64, commits: 32 } },
  { name: 10, value: { hours: 68, commits: 34 } },
  { name: 11, value: { hours: 62, commits: 31 } },
  { name: 12, value: { hours: 94, commits: 47 } },
  { name: 13, value: { hours: 194, commits: 97 } },
  { name: 14, value: { hours: 110, commits: 55 } },
  { name: 15, value: { hours: 146, commits: 73 } },
  { name: 16, value: { hours: 138, commits: 69 } },
  { name: 17, value: { hours: 124, commits: 62 } },
  { name: 18, value: { hours: 72, commits: 36 } },
  { name: 19, value: { hours: 72, commits: 36 } },
  { name: 20, value: { hours: 42, commits: 21 } },
  { name: 21, value: { hours: 144, commits: 72 } },
  { name: 22, value: { hours: 100, commits: 50 } },
  { name: 23, value: { hours: 54, commits: 27 } },
  { name: 24, value: { hours: 138, commits: 69 } },
  { name: 25, value: { hours: 14, commits: 7 } },
  { name: 26, value: { hours: 50, commits: 25 } },
  { name: 27, value: { hours: 82, commits: 41 } },
  { name: 28, value: { hours: 58, commits: 29 } },
  { name: 29, value: { hours: 110, commits: 55 } },
  { name: 30, value: { hours: 114, commits: 57 } },
  { name: 31, value: { hours: 92, commits: 46 } },
  { name: 32, value: { hours: 54, commits: 27 } },
  { name: 33, value: { hours: 48, commits: 24 } },
  { name: 34, value: { hours: 50, commits: 25 } },
  { name: 35, value: { hours: 44, commits: 22 } },
  { name: 36, value: { hours: 56, commits: 28 } },
  { name: 37, value: { hours: 76, commits: 38 } },
  { name: 38, value: { hours: 62, commits: 31 } },
  { name: 39, value: { hours: 52, commits: 26 } },
  { name: 40, value: { hours: 84, commits: 42 } },
  { name: 41, value: { hours: 24, commits: 12 } },
  { name: 42, value: { hours: 68, commits: 34 } },
  { name: 43, value: { hours: 36, commits: 18 } },
  { name: 44, value: { hours: 36, commits: 18 } },
  { name: 45, value: { hours: 54, commits: 27 } },
  { name: 46, value: { hours: 134, commits: 67 } },
  { name: 47, value: { hours: 108, commits: 54 } },
  { name: 48, value: { hours: 122, commits: 61 } },
  { name: 49, value: { hours: 106, commits: 53 } },
  { name: 50, value: { hours: 46, commits: 23 } },
  { name: 51, value: { hours: 150, commits: 75 } },
  { name: 52, value: { hours: 62, commits: 31 } },
];

export const totalHours = 4234;
